baseURL = 'https://georgefb.com/'
languageCode = 'en-us'
title = 'g-fb'
theme = 'PaperMod'

[[menu.main]]
identifier = 'projects'
name = 'Projects'
url = '/projects/'
weight = 10

[taxonomies]
tag = 'tags'

[params]
mainSections = 'blog'
comments = true

[permalinks]
[permalinks.page]
blog = 'blog/:slug'

[privacy]
[privacy.youtube]
disable = false
privacyEnhanced = true

[markup.goldmark.renderer]
unsafe = true
